Support for publishing events over RabbitMQ when TruckDriveStates are created
Metatavu/vp-kuljetus-vehicle-management-service-api pull request #78
Opened 2024-08-29 04:47 UTC by villejuutila

- Also renamed generated packages to better support multi modules
- Added support for tests MessagingClient to consume messages

Resolves #77

2024-08-29 07:43 UTC, anttileppa requested changes

2024-08-29 07:43 UTC, anttileppa commented on src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TrucksApiImpl.kt
> +        eventBus.publish(TruckDriveStateCreatedConsumer.TRUCK_DRIVE_STATE_CREATED, createdDriveState)
Is there any particular reason why this is not in the controller?

2024-08-29 07:43 UTC, anttileppa commented on src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/settings/DefaultTestProfile.kt
> +        config["mp.messaging.incoming.vp-in.connector"] = "smallrye-rabbitmq"
Isn't it always rabbitmq? If it is then why this is defined in the test, not in the application.properties

2024-08-29 07:43 UTC, anttileppa commented on src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/settings/DefaultTestProfile.kt
> +//        config["mp.messaging.incoming.vp-in.queue.name"] = "incoming_queue"
Remove commented code

2024-08-29 09:04 UTC, villejuutila commented on src/main/kotlin/fi/metatavu/vp/vehiclemanagement/trucks/TrucksApiImpl.kt
> +        eventBus.publish(TruckDriveStateCreatedConsumer.TRUCK_DRIVE_STATE_CREATED, createdDriveState)
Not really. Moved there if that's more appropriate

2024-08-29 09:48 UTC, villejuutila commented on src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/settings/DefaultTestProfile.kt
> +//        config["mp.messaging.incoming.vp-in.queue.name"] = "incoming_queue"
Resolved

2024-08-29 10:25 UTC, villejuutila commented on src/test/kotlin/fi/metatavu/vp/vehiclemanagement/test/functional/settings/DefaultTestProfile.kt
> +        config["mp.messaging.incoming.vp-in.connector"] = "smallrye-rabbitmq"
Good point. Moved.

2024-09-02 04:08 UTC, anttileppa approved these changes

2024-09-02 05:46 UTC, merged